# Generated by Django 4.0.4 on 2022-05-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='tariff',
            new_name='tariff_per_M',
        ),
    ]
